package org.refactoringminer.csharp;

import gr.uom.java.xmi.UMLModel;
import gr.uom.java.xmi.UMLModelASTReader;

import java.util.HashMap;
import java.util.Map;
import java.util.Set;

import org.eclipse.jdt.core.dom.CompilationUnit;

/**
 * CSharpUMLModelASTReader - Creates UMLModel from CPatMiner generated AST
 * 
 * This class extends the standard UMLModelASTReader to work with CompilationUnit ASTs
 * generated by CPatMiner from C# source code, providing proper integration between
 * CPatMiner's AST output and RefactoringMiner's UMLModel system.
 */
public class CSharpUMLModelASTReader extends UMLModelASTReader {

    /**
     * Create UMLModel from C# file contents using CPatMiner AST generation
     * 
     * @param fileContents Map of file paths to C# source code content
     * @param repositoryDirectories Set of repository directories
     * @param storeUnchangedEntities Whether to store unchanged entities
     * @throws Exception if AST generation or UMLModel creation fails
     */
    public CSharpUMLModelASTReader(Map<String, String> fileContents, Set<String> repositoryDirectories, boolean storeUnchangedEntities) throws Exception {
        super(processFilesWithCPatMiner(fileContents), repositoryDirectories, storeUnchangedEntities);
        System.out.println("CSharpUMLModelASTReader: Created UMLModel with CPatMiner AST integration");
    }
    
    /**
     * Process files using CPatMiner to generate proper Java AST, then convert to string format
     * for the parent UMLModelASTReader
     * 
     * @param fileContents Original file contents (may include C# files)
     * @return Processed file contents with C# files converted to Java via CPatMiner AST
     */
    private static Map<String, String> processFilesWithCPatMiner(Map<String, String> fileContents) {
        System.out.println("CSharpUMLModelASTReader: Processing files with CPatMiner AST integration");
        
        Map<String, String> processedContents = new HashMap<>();
        
        // First, get AST representations from CPatMiner for C# files
        Map<String, CompilationUnit> csharpAsts = CPatMinerExecutor.processCSharpFiles(fileContents);
        
        // Convert ASTs back to string format for UMLModelASTReader
        for (Map.Entry<String, CompilationUnit> entry : csharpAsts.entrySet()) {
            String filePath = entry.getKey();
            CompilationUnit ast = entry.getValue();
            
            String javaCode = CPatMinerExecutor.astToString(ast);
            if (javaCode != null && !javaCode.trim().isEmpty()) {
                processedContents.put(filePath, javaCode);
                System.out.println("CSharpUMLModelASTReader: Added AST-generated Java code for: " + filePath + 
                                 " (" + javaCode.length() + " chars)");
            } else {
                System.err.println("CSharpUMLModelASTReader: Failed to convert AST to string for: " + filePath);
            }
        }
        
        // Also include any Java files that were already present
        for (Map.Entry<String, String> entry : fileContents.entrySet()) {
            String filePath = entry.getKey();
            String content = entry.getValue();
            
            if (isJavaFile(filePath)) {
                processedContents.put(filePath, content);
                System.out.println("CSharpUMLModelASTReader: Included existing Java file: " + filePath);
            }
        }
        
        System.out.println("CSharpUMLModelASTReader: Total processed files: " + processedContents.size());
        return processedContents;
    }
    
    /**
     * Check if a file is a Java source file
     */
    private static boolean isJavaFile(String filePath) {
        return filePath != null && filePath.toLowerCase().endsWith(".java");
    }
}